# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sciencenews',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_module', models.CharField(default='News', max_length=30)),
                ('second_module', models.CharField(default='Latest News', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=60, null=True)),
                ('publish_date', models.CharField(max_length=35, null=True)),
                ('content', models.TextField(null=True)),
                ('crawl_date', models.CharField(max_length=35, null=True)),
                ('from_url', models.CharField(max_length=350, null=True)),
            ],
        ),
    ]
