# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('newsuuid', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=60)),
                ('vicetitle', models.CharField(max_length=60)),
                ('source', models.CharField(max_length=60)),
                ('newscontent', models.CharField(max_length=5000)),
                ('imageone', models.CharField(max_length=600)),
                ('imagetwo', models.CharField(max_length=600)),
                ('imagethree', models.CharField(max_length=600)),
                ('newsurl', models.CharField(max_length=600)),
                ('newstype', models.CharField(max_length=10)),
                ('lable', models.CharField(max_length=60)),
            ],
        ),
    ]
