# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_sciencenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='djangoMysqlTest',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('djangoUUI', models.CharField(max_length=30)),
                ('book', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
