# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publishdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='imageone',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='imagethree',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='imagetwo',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='lable',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='newscontent',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='newstype',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsurl',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='vicetitle',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
