# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171011_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpadmin',
            fields=[
                ('adminid', models.BigAutoField(primary_key=True, serialize=False)),
                ('adminuuid', models.CharField(max_length=60)),
                ('adminname', models.CharField(max_length=60)),
                ('adminpasswd', models.CharField(max_length=60)),
            ],
        ),
    ]
