# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_djangomysqltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True)),
                ('ip_addr', models.GenericIPAddressField()),
                ('port', models.SmallIntegerField(default=22)),
                ('system_type', models.SmallIntegerField(choices=[(0, 'Linux'), (1, 'Windows')], default=0)),
                ('memo', models.CharField(blank=True, max_length=128, null=True)),
                ('enabled', models.BooleanField(default=1, verbose_name='启用本机')),
            ],
            options={
                'verbose_name': '主机表',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('ip_addr', 'port')]),
        ),
    ]
