# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20171010_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
