# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_usertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='userDate',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
