# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_fruit_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScienceNews',
        ),
        migrations.DeleteModel(
            name='UserInfor',
        ),
    ]
