# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_usertest_userdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='userDate',
        ),
        migrations.AddField(
            model_name='usertest',
            name='userPass',
            field=models.CharField(db_column='userPass', default="", max_length=30),
            preserve_default=False,
        ),
    ]
