# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_userc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accountUUID', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'userAccount',
            },
        ),
    ]
