# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweetid', models.BigAutoField(primary_key=True, serialize=False)),
                ('tweetuuid', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tweet',
            },
        ),
    ]
